/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sundae_ndktest_MainActivity */

#ifndef _Included_com_sundae_ndktest_MainActivity
#define _Included_com_sundae_ndktest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sundae_ndktest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sundae_ndktest_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_sundae_ndktest_MainActivity
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sundae_ndktest_MainActivity_getStringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sundae_ndktest_MainActivity
 * Method:    getBitmap
 * Signature: (III)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_sundae_ndktest_MainActivity_getBitmap
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sundae_ndktest_MainActivity
 * Method:    getGrayImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_sundae_ndktest_MainActivity_getGrayImage
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
